[package]
name = "arctis-rs"
version = "0.1.5"
authors = ["Nguyen Thai"]
edition = "2018"

[dependencies]
hidapi = "1.2.6"
color-eyre = { version = "0.6", default-features = false }
clap = { version = "4.1.4", features = ["derive", "wrap_help", "cargo"] }
