[package]
name = "arctis-rs"
version = "0.1.10"
authors = ["Nguyen Thai"]
edition = "2024"

[dependencies]
hidapi = "2.6"
color-eyre = { version = "0.6", default-features = false }
clap = { version = "4.5", features = ["derive", "wrap_help", "cargo"] }

[profile.release]
strip = true
