
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

name: Cross-compile and deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arctis-rs-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/arctis-rs*
            !target/${{ matrix.target }}/release/arctis-rs.d

  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: arctis-rs-${{ matrix.target }}

      - name: Tar up binaries
        run: |
          chmod +x arctis-rs*
          tar czvf arctis-rs-${{ matrix.target }}.tar.gz arctis-rs*

      - name: Publish binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: "arctis-rs*.tar.gz"
          name: "arctis-rs ${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
